### ISSUE TITLE
Write contributing.md document

### ISSUE THREAD

**Issue by awiebe** [Xyrio/RSSOwlnix#10]
I would love to be able to just go in and fix something if it breaks, but I have no idea how the build toolchain works, or what the pieces of RSSOwl do.

e.g. I downloaded this new fork since some feeds were encountering parse errors, but that's fixed so I think you must have built against a newer version of the library responsible for that.

For the continued existence of the RSSOwl project, it would probably be good to document it, if only to help people scavenge it if it dies again.

I would like to know the following:

- What toolchain is used to build RSSOwl?
- What profiles are available to build?
- What command should be issued to build? (Or what steps to take in eclipse.)
- How are dependencies resolved?
- What libraries are used?
- What is in each of the top level folders?
- Is there a roadmap?

**Comment by Xyrio** [comment]
i intend to write a "how to build" at some point, etc. the rssowl program parts im still exploring myself. 

a major problem is that rssowl uses old eclipse stuff. so one needs to learn the older harder way first before one can improve stuff and then learn the newer stuff maybe too to make stuff nicer, maybe.

What toolchain is used to build RSSOwl?
- eclipse's special way (i dislike it)

What profiles are available to build?
- same as current eclipse 4.7 (i built all available, see release page)

What command should be issued to build? (Or what steps to take in eclipse.)
- im doing it manually currently as a product build (in project org.rssowl.ui the rssowl.product file) explaining building is a longer process. mostly because of how to setup up the target platform (menu/window/preferences/plug-in dev/target platform). it is honestly quite time consuming to learn. you probably want to wait until i write some howto or manage to automate and simplify things better.

How are dependencies resolved?
- eclipse osgi

What libraries are used?
- many. most of them from eclipse, swt, httpclient, db4o, jdom, lucene, etc

What is in each of the top level folders?
- roughly explained:
* org.rssowl.build - old ant auto build script but not working currently
* org.rssowl.core - core functionality
* org.rssowl.ui - gui stuff (swt)
* org.rssowl.lib.* - extra libraries in addition to the eclipse ones, needed to make them osgi compatible.
* org.rssowl.update.sites - for creating an update site for auto updating (not working for rssowl itself right now only for plugins and translations is work in progress currently)
* org.rssowl.feature.* - a eclipse "featrue project" for aggregating other "plugin projects" it is for convenience mostly as i understand it.

Is there a roadmap?
- not really. more like a todo list in no special order.
a) im currently trying to get the auto update working. no luck so far.
b) the other major thing on my list is automatically building everything with support for auto update ideally.

once i have those 2 finished or i give up, ill probably write a "how to build" in the wiki here on github.

**Comment by Xyrio** [comment]
https://github.com/Xyrio/RSSOwlnix/wiki/How-To-Build
