### ISSUE TITLE
Feature requests (Portable)

### ISSUE THREAD

**Issue by apstanley** [Xyrio/RSSOwlnix#2]
I'm very excited that someone has decided to pick up RSSOwl. It's the best RSS Reader out there. I do have some suggestions.

It would be great if RSSOwl on Windows could be a portable app. I have this running with 2.1.2 but I can't seem to remember how.

Thanks.

**Comment by Xyrio** [comment]
never tried the portable version. here seems to be the attempt at doing it: https://github.com/rssowl/rssowl-portable

you can try to do it yourself, here is the howto https://github.com/rssowl/rssowl-portable#building

synchronization support depends on how much work it is to do and maintain.

**Comment by Xyrio** [comment]
an experimental way to make rssowl portable for any version is:

example for rssowl 2.2.1 (32bit)

1) copy rssowl folder to like U:\rssowl\RSSOwl.exe

2) (optional, do if you want to copy existing settings and database) copy the data folder (contains settings and database)
from (type in explorer) %userprofile%\.rssowl2\
to like: U:\rssowl\.rssowl2\
so that this path structure exists: 
U:\rssowl\.rssowl2\.metadata
U:\rssowl\.rssowl2\config221

3) change data folder location in U:\rssowl\configuration\config.ini
remove here all @user.home/
like before 
osgi.instance.area.default=@user.home/.rssowl2
osgi.configuration.area=@user.home/.rssowl2/config221
like after
osgi.instance.area.default=.rssowl2
osgi.configuration.area=.rssowl2/config221

4) download and install a jre you want to use (32bit rssowl needs 32bit jre) (2.2.1 needs jre between and including 5 to 8)
after install copy the jre folder and rename it:
like from c:\program files (x86)\java\jre8
to like U:\rssowl\jre\
so that this exists: U:\rssowl\jre\bin\java.exe

done.

on another windows system (32 bit rssowl works also on 64 bit windows) without rssowl and without java installed try running U:\rssowl\RSSOwl.exe

if your database is big running it from a slow device like an usb stick will be obviously slower.

**Comment by apstanley** [comment]
Thanks. I did some digging around the the key is updating the config.ini to
```
osgi.instance.area.default=.rssowl2
osgi.configuration.area=.rssowl2/config221
```
It just took me a while to find it. Sorry about that.

We should probably create a new issue for syncing and close this issue.

**Comment by Xyrio** [comment]
added -Dportable above

**Comment by Joel889** [comment]
This doesn't seem to work when installing add-ons.

**Comment by Xyrio** [comment]
might be related to #5 that you need to change path in the config.ini again because it gets reset.
