### ISSUE TITLE
Feed not parsed correctly, missing entries

### ISSUE THREAD

**Issue by wildcat37** [Xyrio/RSSOwlnix#73]
[feed.txt](https://github.com/Xyrio/RSSOwlnix/files/3825250/feed.txt)

RSSOwl and now RSSOwlnix doesn't parse the feed correctly and some entries do not show up.
I'm importing the local feed using this path: file:///F:/feed.txt

The attached feed shows the bug.

When the feed is imported, the entry with the title "8-K - CONSOLIDATED EDISON CO OF NEW YORK INC (0000023632) (Filer)" does not show up in RSSOwl/RSSOwlnix.

Please fix.

**Comment by Xyrio** [comment]
that is because the id is the same `
<id>urn:tag:sec.gov,2008:accession-number=0001047862-19-000194</id>` so it is understood as an update to the older one. you can manipulate the id to never be the same as a previous one at least within the same file.

this would require a new feature to never do news updates but instead create a new news entry by manipulating the ids.

**Comment by wildcat37** [comment]
thanks for the feedback

**Comment by Xyrio** [comment]
since 2.8.0 one can use shell:// protocol to do such tricks externally
