### ISSUE TITLE
Error when trying to start version 2-7-1

### ISSUE THREAD

**Issue by Echtze1t** [Xyrio/RSSOwlnix#85]
I just updated to the latest version (from previous 2-7-0), but now get an error when starting RSSOwlnix.

I have attached the .log file

[1584694764240.log](https://github.com/Xyrio/RSSOwlnix/files/4358643/1584694764240.log)

**Comment by Xyrio** [comment]
what OS?

**Comment by Xyrio** [comment]
hmm no idea so far. try moving the .rssowlnix-beta homefolder and start fresh see if it works.
you can copy the database over afterwards (after clearing newly created db)

home: %userprofile%\.rssowlnix-beta (move the folder into another subfolder, because of name starting with dot windows does not like it)
db stuff located under: .rssowlnix-beta\.metadata\.plugins\org.rssowl.core

**Comment by Echtze1t** [comment]
That worked. Thanks!

**Comment by Xyrio** [comment]
unknown bug cannot fix. since workaround works i am closing this.
