### ISSUE TITLE
HowTo Manual Update RSSOwlnix

### ISSUE THREAD

**Issue by ErikBrown2** [Xyrio/RSSOwlnix#89]
Hi,

Thanks for maintaining RSSOwl(nix). I use the software already for years and years daily and enjoy it very much. This is the first time that I want to upgrade RSSOwlnix to a newer version but there appears not to be a installation/upgrade executable. Only a compressed set of files. This is fine but what are the instructions for using these files? Should I just overwrite the old files or should I uninstall the old installation first? 

Also the description of the data folder is not very clear for computer illiterates. Where do I find the folders @user.home/.rssowl2, @user.home/.rssowl2-beta and @.home/.rssowlnix-betauser ?

After some Googling I found that this must be C:\Users\<my username>.rssowl...
Maybe it would be handy to mention that in the upgrade announcement.

Thanks again for all the work to maintain this great application.

**Comment by Xyrio** [comment]
on windows @user.home is same as %userprofile% which can by typed in explorer addressbar.
the .rssowl* folders are from the different versions that you might be updating from:
- .rssowl2 is the original
- .rssowl2-beta is from older rssowlnix forks
- .rssowlnix-beta is the current one

if you are updating from older rssowlnix to later one you can just replace the RSSOwlnix folder of the old installation and leave the .rssowlnix-beta folder as is. rename old one if you want to maybe go back or have changed *.ini files manually. then unzip new one to fit previous folder structure so your shortcuts continue to work. afterward you may redo whatever manual *.ini file changes you maybe did.

if you had addons installed it will prompt you on first start. if you changed the default .rssowlnix-beta location you will have to change the config.ini inside the .rssowlnix-beta folder afterwards again before the rssowlnix restart due to a bug.

**Comment by ErikBrown2** [comment]
Thanks for the detailed reply. When upgrading from RSSOwlnix 2.71, is it not possible to keep automatically the changes previously made? I had modified the fonts in multiple locations. Can I somehow copy the old configuration file to the new application version?

**Comment by karnrage** [comment]
Does the .ini file have the list of all the old RSS feeds? If so can I drag and drop into the new install?

**Comment by Xyrio** [comment]
as i wrote above: `at least the contents of .rssowlnix-beta\.metadata\.plugins\org.rssowl.core which is the database` thats where the rss feeds and content so far are saved.
