### ISSUE TITLE
Can't access to 127.0.0.1:8795

### ISSUE THREAD

**Issue by Martyprod** [Xyrio/RSSOwlnix#96]
Hello, i had this error with the original RSSOwl, sometimes it was stopping to do it after a reboot.

i just upgraded to RSSOwlnix, and error is still there 

"can't access to this page.
Check web adress http://127.0.0.1:8795 is correct"

Thanks for any help.

**Comment by Xyrio** [comment]
that port is used by the internal browser: https://github.com/Xyrio/RSSOwlnix/wiki/FAQ#item_6a

there are 3 possibilites:
- maybe your firewall blocked it
- it is used by another program
- the port has not been released yet

i asume you are not running multiple rssowl* at the same time.

you could check who uses open ports like described further below,

or try different ports randomly in the range of 8000 to 50000 a few times. 
to change the port add a line to the rssownlix.ini containing `-Dport=8796` after any other line that starts with `-D` (there should be only one line starting with `-Dport=`). then change the number and (re)start rssownix for it to take effect.

if different ports do not work it is probably the firewall. the windows firewall usually does not block ports on 127.0.0.1 but if you have another one installed it may be more aggressive.

# checking open ports:
you can check with the (task manager) resource monitor (on windows) what tcp listening ports are in use (exists since win7 and is located a little different each windows, google it if you dont know), here is an example of how resource monitor looks: https://tr1.cbsistatic.com/hub/i/2015/05/07/cd486460-f498-11e4-940f-14feb5cc3d2a/resourcemonitor-net-figa0729.jpg
the listening ports part at the bottom is where you find currently open ports.

or you can open a console window and type `netstat -ano | find ":8795"` to if that port is in use. the right most number is the process id which you can look up in task manager to find out what program already uses that port.

if the port is used by rssowlnix then it is probably your firewall that block that ports. or with a smaller chance the port is not free yet.

**Comment by Martyprod** [comment]
Hi thanks for the help ! 

in fact i get an error message as soon as i start the software :
RssOwlnix is unable to start a local server for displaying news. Please Ensure that no firewall is blocking RossOwlnix from opening port 8795 on the loopback network 127.0.0.1

I have a friend who is a programmer (it's his job) and told me to do a netstat this morning and no port 8795 were present in the list

No it's not blocked by my firewall, (tried without it / turned off). 
I only use Windows Defender and the windows firewall control from Malwarebyes.
in the resource monitor, nobody use 8795. only one use 127.0.0.1 right now, it's pidgin.

i Noticed that sometimes after a reboot, it's working, and like today, it display this message and I can't do nothing. even after a reboot, it's still the same and sometimes it's working.

i tried your command "netstat -ano | find ":8795"
(the find one gave "unknown "find" command"

so just checking with netstat -ano and found no 8795 anywhere. 

the list of news is updated by RSSowlnix, but it's unable to display it in the internal browser (even if i use chrome instead of the pure internal one from the software).

I'll try the "change port" idea in the ini ! and will report back if it worked, thank you a lot for the help !

**Comment by Xyrio** [comment]
find command should exist from win7+. what is your OS?

**Comment by Martyprod** [comment]
Windows 10 last version (2004). yes i will try that, thanks !

**Comment by Martyprod** [comment]
Hi again, this solution fixed the problem !!  i put a number above 17000 !

"to change the port add a line to the rssownlix.ini containing -Dport=8796 after any other line that starts with -D (there should be only one line starting with -Dport= within the file). then change the number and (re)start rssownix for it to take effect."

Thank You !!
